name: Lint and Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
